DjangoBD/urls.py
from django.contrib import admin
from django.urls import path,include, re_path

from catalog.views import *
from rest_framework import routers
urlpatterns = [
    path('admin/', admin.site.urls),
]

#Авторизация
urlpatterns += [
    path('api/v1/drf-auth/',include('rest_framework.urls')), #http://127.0.0.1:8000/api/v1/drf-auth/login/(logout)
    
]
#Токен
urlpatterns += [
    path('api/v1/auth/',include('djoser.urls')), 
    re_path(r'^auth/',include('djoser.urls.authtoken')),
]
# class MyCustomRouter(routers.SimpleRouter):
#     routes = [
#         routers.Route(url=r'^{prefix}$',
#                       mapping={'get': 'list'},
#                       name='{basename}-list',
#                       detail=False,
#                       initkwargs={'suffix': 'List'}),
#         routers.Route(url=r'^{prefix}/{lookup}$',
#                       mapping={'get': 'retrieve'},
#                       name='{basename}-detail',
#                       detail=True,
#                       initkwargs={'suffix': 'Detail'})
#     ]
# router = MyCustomRouter() - роутер где будет находить страницу без последнего слешла  http://127.0.0.1:8000/api/v1/facultet (работает как SimpleRouter)

router=routers.DefaultRouter() # - #http://127.0.0.1:8000/api/v1/ есть путь (показывает куда идти) router=routers.SimpleRouter() - нет пути

router.register(r'facultet',FacultetViewSet)
urlpatterns += [path('api/v1/',include(router.urls)),]
router.register(r'napravlenie',NapravlenieViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'group',GroupViewSet)
urlpatterns += [path('api/v1/',include(router.urls)),]
router.register(r'studenti',StudentiViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'jurnal',JurnalViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'ficsation',FicsationViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'rabotnik',RabotnikViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'forma_kontrol9',Forma_kontrol9ViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]
router.register(r'predmet',PredmetViewSet)
urlpatterns += [path('api/v1/',include(router.urls)), ]




# Используйте include() чтобы добавлять URL из каталога приложения
from django.urls import include
urlpatterns += [
     path('catalog/', include('catalog.urls')),
]

# Добавьте URL соотношения, чтобы перенаправить запросы с корневого URL, на URL приложения
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Используйте static() чтобы добавить соотношения для статических файлов
# Только на период разработки
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^facultets/$', views.FacultetListView.as_view(), name='facultets'),
    url(r'^facultet/(?P<pk>\d+)$', views.FacultetDetailView.as_view(), name='facultet-detail'),
    
    url(r'^napravlenies/$', views.NapravlenieListView.as_view(), name='napravlenies'),
    url(r'^napravlenie/(?P<pk>\d+)$', views.NapravlenieDetailView.as_view(), name='napravlenie-detail'),

    url(r'^groups/$', views.GroupListView.as_view(), name='groups'),
    url(r'^group/(?P<pk>\d+)$', views.GroupDetailView.as_view(), name='group-detail'),

    url(r'^predmets/$', views.PredmetListView.as_view(), name='predmets'),
    url(r'^predmet/(?P<pk>\d+)$', views.PredmetDetailView.as_view(), name='predmet-detail'),

    url(r'^forma_kontrol9s/$', views.Forma_kontrol9ListView.as_view(), name='forma_kontrol9s'),
    url(r'^forma_kontrol9/(?P<pk>\d+)$', views.Forma_kontrol9DetailView.as_view(), name='forma_kontrol9-detail'),

    url(r'^jurnals/$', views.JurnalListView.as_view(), name='jurnals'),
    url(r'^jurnal/(?P<pk>\d+)$', views.JurnalDetailView.as_view(), name='jurnal-detail'),

    url(r'^ficsations/$', views.FicsationListView.as_view(), name='ficsations'),
    url(r'^ficsation/(?P<pk>\d+)$', views.FicsationDetailView.as_view(), name='ficsation-detail'),

    url(r'^rabotniks/$', views.RabotnikListView.as_view(), name='rabotniks'),
    url(r'^rabotnik/(?P<pk>\d+)$', views.RabotnikDetailView.as_view(), name='rabotnik-detail'),

    url(r'^studentis/$', views.StudentiListView.as_view(), name='studentis'),
    url(r'^studenti/(?P<pk>\d+)$', views.StudentiDetailView.as_view(), name='studenti-detail'),
]


urlpatterns += [
    url(r'^facultet/create/$', views.FacultetCreate.as_view(), name='facultet_create'),
    url(r'^facultet/(?P<pk>\d+)/update/$', views.FacultetUpdate.as_view(), name='facultet_update'),
    url(r'^facultet/(?P<pk>\d+)/delete/$', views.FacultetDelete.as_view(), name='facultet_delete'),

    url(r'^napravlenie/create/$', views.NapravlenieCreate.as_view(), name='napravlenie_create'),
    url(r'^napravlenie/(?P<pk>\d+)/update/$', views.NapravlenieUpdate.as_view(), name='napravlenie_update'),
    url(r'^napravlenie/(?P<pk>\d+)/delete/$', views.NapravlenieDelete.as_view(), name='napravlenie_delete'),

    url(r'^group/create/$', views.GroupCreate.as_view(), name='group_create'),
    url(r'^group/(?P<pk>\d+)/update/$', views.GroupUpdate.as_view(), name='group_update'),
    url(r'^group/(?P<pk>\d+)/delete/$', views.GroupDelete.as_view(), name='group_delete'),

    url(r'^predmet/create/$', views.PredmetCreate.as_view(), name='predmet_create'),
    url(r'^predmet/(?P<pk>\d+)/update/$', views.PredmetUpdate.as_view(), name='predmet_update'),
    url(r'^predmet/(?P<pk>\d+)/delete/$', views.PredmetDelete.as_view(), name='predmet_delete'),

    url(r'^forma_kontrol9/create/$', views.Forma_kontrol9Create.as_view(), name='forma_kontrol9_create'),
    url(r'^forma_kontrol9/(?P<pk>\d+)/update/$', views.Forma_kontrol9Update.as_view(), name='forma_kontrol9_update'),
    url(r'^forma_kontrol9/(?P<pk>\d+)/delete/$', views.Forma_kontrol9Delete.as_view(), name='forma_kontrol9_delete'),

    url(r'^jurnal/create/$', views.JurnalCreate.as_view(), name='jurnal_create'),
    url(r'^jurnal/(?P<pk>\d+)/update/$', views.JurnalUpdate.as_view(), name='jurnal_update'),
    url(r'^jurnal/(?P<pk>\d+)/delete/$', views.JurnalDelete.as_view(), name='jurnal_delete'),

    url(r'^ficsation/create/$', views.FicsationCreate.as_view(), name='ficsation_create'),
    url(r'^ficsation/(?P<pk>\d+)/update/$', views.FicsationUpdate.as_view(), name='ficsation_update'),
    url(r'^ficsation/(?P<pk>\d+)/delete/$', views.FicsationDelete.as_view(), name='ficsation_delete'),


    url(r'^rabotnik/create/$', views.RabotnikCreate.as_view(), name='rabotnik_create'),
    url(r'^rabotnik/(?P<pk>\d+)/update/$', views.RabotnikUpdate.as_view(), name='rabotnik_update'),
    url(r'^rabotnik/(?P<pk>\d+)/delete/$', views.RabotnikDelete.as_view(), name='rabotnik_delete'),

    url(r'^studenti/create/$', views.StudentiCreate.as_view(), name='studenti_create'),
    url(r'^studenti/(?P<pk>\d+)/update/$', views.StudentiUpdate.as_view(), name='studenti_update'),
    url(r'^studenti/(?P<pk>\d+)/delete/$', views.StudentiDelete.as_view(), name='studenti_delete'),
]

catalog/models.py
from django.db import models
from django.urls import reverse #Используется для создания URL-адресов путем изменения шаблонов URL-адресов.
import uuid # Требуется для уникальных экземпляров 

class Facultet(models.Model):
    """Модель, представляющая Факультет."""
    #id = models.IntegerField(primary_key=True,db_index=True, help_text="Уникальный индификатор")
    id = models.AutoField(primary_key=True)
    name_faculteta = models.CharField(max_length=100, help_text="Введите абривиатуру (название) факультета ")
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('facultet-detail', args=[str(self.id)])    
    def __str__(self):
# чтобы вернуть удобочитаемую строку для каждого объекта. 
# Эта строка используется для представления отдельных записей на сайте администрирования 
# (и в любом другом месте, где вам нужно обратиться к экземпляру модели). 
# Часто это возвращает поле названия или имени из модели.
        return '%s ' % (self.name_faculteta)
    class Meta:
        ordering = ['name_faculteta']


class Napravlenie(models.Model):
    """Модель, представляющая Направление."""
    id = models.AutoField(primary_key=True)
    name_napravlenie = models.CharField(max_length=100, help_text="Введите номер (название) направления ")
    id_facultet = models.ForeignKey('Facultet', on_delete=models.PROTECT, null=False) #PROTECT (Нельзя будет удалить запись указанной таблицы пока он привязан к какой-то таблице)
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('napravlenie-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s %s' % (self.name_napravlenie,self.id_facultet.name_faculteta)
    class Meta:
        ordering = ['name_napravlenie']


class Group(models.Model):
    """Модель, представляющая Группу."""
    id = models.AutoField(primary_key=True)
    name_group = models.CharField(max_length=50, help_text="Введите номер (название) группы ")
    id_napravlenie = models.ForeignKey('Napravlenie', on_delete=models.PROTECT, null=False)
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('group-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s (%s)' % (self.name_group,self.id_napravlenie)
    class Meta:
        ordering = ['name_group','-id_napravlenie']

class Studenti(models.Model):
    """Модель, представляющая Студентов. """
    id = models.AutoField(primary_key=True)
    last_name = models.CharField(max_length=100,null=True)
    first_name = models.CharField(max_length=100,null=True)
    middle_name = models.CharField(max_length=100,null=True)
    id_groupa = models.ForeignKey('Group', on_delete=models.PROTECT, null=False)

    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('studenti-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s %s %s [%s]' % (self.last_name,self.first_name,self.middle_name, 
        self.id_groupa)

    class Meta:
        ordering = ['last_name']

###############################################################################################


class Rabotnik(models.Model):
    """Модель, представляющая Работника. """
    id = models.AutoField(primary_key=True)
    last_name = models.CharField(max_length=100,null=True)
    first_name = models.CharField(max_length=100,null=True)
    middle_name=models.CharField(max_length=100,null=True)
    
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('rabotnik-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s %s %s' % (self.last_name,self.first_name,self.middle_name)
    class Meta:
        ordering = ['last_name']



###############################################################################################
class Forma_kontrol9(models.Model):
    """Модель, представляющая Форму контроля."""
    id = models.AutoField(primary_key=True)
    vid_formi = models.CharField(max_length=50, help_text="Введите вид занятия (Например лекция, практическое занятие, лабараторное) ")
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('forma_kontrol9-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s ' % (self.vid_formi)

class Predmet(models.Model):
    """Модель, представляющая Предмет. """
    id = models.AutoField(primary_key=True)
    name_predmeta = models.CharField(max_length=70,help_text="Введите название предмета")
    id_forma_kontrol9 = models.ForeignKey('Forma_kontrol9', on_delete=models.PROTECT, null=False) #PROTECT (Вид занятия нельзя будет удалить пока он привязан к какой-то таблице)
    
    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('predmet-detail', args=[str(self.id)])    
    def __str__(self):
        return '%s (%s)' % (self.name_predmeta,self.id_forma_kontrol9.vid_formi)



###############################################################################################
###############################################################################################


class Jurnal(models.Model):
    """Модель, представляющая Предмет. """
    id = models.AutoField(primary_key=True)
    id_rabotnika = models.ForeignKey('Rabotnik', on_delete=models.PROTECT, null=False) #PROTECT (Вид занятия нельзя будет удалить пока он привязан к какой-то таблице)
    id_predmeta = models.ForeignKey('Predmet', on_delete=models.PROTECT, null=False)
    id_studentov = models.ForeignKey('Studenti', on_delete=models.CASCADE, null=False)


    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('jurnal-detail', args=[str(self.id)])    
    def __str__(self):
        return '[%s] %s %s %s  ' % (self.id,
        self.id_rabotnika,self.id_predmeta,self.id_studentov)
    class Meta:
        ordering = ['id_predmeta','id_rabotnika','id_studentov']
        
    
###############################################################################################
class Ficsation(models.Model):
    """Модель, представляющая Фиксацию. """
    id = models.AutoField(primary_key=True)
    id_nomer_zapisi = models.ForeignKey('Jurnal', on_delete=models.CASCADE, null=False) 
    data_propyskov = models.DateField(null=True, blank=True)
    propyski = models.BooleanField (default=True,help_text="Присутсвовал/Отсутсвовал")
    opisanie = models.TextField(max_length=1000,null=True,blank=True, help_text="Описание")


    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному ."""
        return reverse('ficsation-detail', args=[str(self.id)])    
    def __str__(self):
        return '[%s] %s %s %s %s   ' % (self.id,self.id_nomer_zapisi,
        self.data_propyskov,self.propyski,self.opisanie)

    class Meta:
        ordering = ['-data_propyskov']

catalog/templates/catalog/facultet_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the facultet: {{ facultet }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/facultet_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/forma_kontrol9_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the forma_kontrol9: {{ forma_kontrol9 }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/group_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ group.name_group }}</h1>
  <li><a href="{% url 'group_update' group.pk %}">Изменить </a></li>
  <li><a href="{% url 'group_delete' group.pk %}">Удалить</a></li>
  <p><strong>Napravlenie:</strong> <a href="{% url 'napravlenie-detail' group.id_napravlenie.pk %}">{{ group.id_napravlenie }}</a></p> 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Students</h4>

    {% for copy in group.studenti_set.all %}
    <hr>
    <p><strong>Last_name:</strong> {{copy.last_name}}</p>
    <p><strong>First_name:</strong> {{copy.first_name}}</p>
    <p><strong>Middle_name:</strong> {{copy.middle_name}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/group_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/jurnal_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/napravlenie_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ napravlenie.name_napravlenie }}</h1>
  <li><a href="{% url 'napravlenie_update' napravlenie.pk %}">Изменить </a></li>
  <li><a href="{% url 'napravlenie_delete' napravlenie.pk %}">Удалить</a></li>
  <p><strong>Facultet:</strong> <a href="{% url 'facultet-detail' napravlenie.id_facultet.pk %}">{{ napravlenie.id_facultet }}</a></p> <!-- author detail link not yet defined -->

  <div style="margin-left:20px;margin-top:20px">
    <h4>Groups</h4>

    {% for copy in napravlenie.group_set.all %}
    <hr>
    <p><strong>Name:</strong> <a href="{% url 'group-detail' copy.id_napravlenie.pk %}">{{ copy.name_group }}</a></p> 
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/predmet_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Predmet List</h1>
    {% if user.is_authenticated %}
          <li><a href="{% url 'predmet_create'%}"> Добавить Предмет</a></li>
    {% endif %}
    {% if predmet_list %}
    <ul>

      {% for predmet in predmet_list %}
      <li>
        <a href="{{ predmet.get_absolute_url }}">{{ predmet.name_predmeta }}</a> ({{predmet.id_forma_kontrol9}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no predmets in the library.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/rabotnik_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the rabotnik: {{ rabotnik }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/rabotnik_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/rabotnik_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>rabotnik List</h1>
    {% if user.is_authenticated %}
          <li><a href="{% url 'rabotnik_create'%}"> Добавить Работника</a></li>
    {% endif %}
    {% if rabotnik_list %}
    <ul>

      {% for rabotnik in rabotnik_list %}
      <li>
        <a href="{{ rabotnik.get_absolute_url }}"> {{rabotnik.last_name}} {{rabotnik.first_name}} {{rabotnik.middle_name}}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no rabotnik in the library.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/studenti_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{studenti.last_name}} {{studenti.first_name}} {{studenti.middle_name}}</h1>
  <li><a href="{% url 'studenti_update' studenti.pk %}">Изменить </a></li>
  <li><a href="{% url 'studenti_delete' studenti.pk %}">Удалить</a></li>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Журнал</h4>

    {% for copy in studenti.jurnal_set.all %}
    <hr>
    <p><strong>Id_predmeta:</strong> <a href="{% url 'predmet-detail' copy.id_predmeta.pk %}">{{ copy.id_predmeta }}</a></p>
    <p><strong>Id_rabotnika:</strong> <a href="{% url 'rabotnik-detail' copy.id_rabotnika.pk %}">{{ copy.id_rabotnika }}</a></p>
    <p><strong>Data_propyskov:</strong> {{ copy.data_propyskov }}</p>
    <p><strong>Propyski:</strong> {{copy.propyski}}</p>
    <p><strong>Opisanie:</strong> {{copy.opisanie }}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/studenti_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/studenti_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Студенты List</h1>
    {% if user.is_authenticated %}
          <li><a href="{% url 'studenti_create'%}"> Добавить Студента</a></li>
    {% endif %}
    {% if studenti_list %}
    <ul>

      {% for studenti in studenti_list %}
      <li>
        <a href="{{ studenti.get_absolute_url }}"> {{studenti.last_name}} {{studenti.first_name}} {{studenti.middle_name}}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no studentik in the library.</p>
    {% endif %} 
{% endblock %}